export const mockChats = [
  { id: "1", title: "Crear componente React básico", createdAt: "hace 5 minutos" },
  { id: "2", title: "Cómo usar useEffect correctamente", createdAt: "hace 20 minutos" },
  { id: "3", title: "Diferencia entre useMemo y useCallback", createdAt: "hace 1 hora" },
  { id: "4", title: "Configurar TanStack Query en Next.js", createdAt: "ayer" },
  { id: "5", title: "Cómo tipar correctamente con TypeScript", createdAt: "ayer" },
  { id: "6", title: "Autenticación con JWT y refresh tokens", createdAt: "hace 2 días" },
  { id: "7", title: "Diseñar una REST API con Express", createdAt: "hace 2 días" },
  { id: "8", title: "Optimizar consultas en PostgreSQL", createdAt: "hace 3 días" },
  { id: "9", title: "Implementar WebSockets en Node.js", createdAt: "hace 4 días" },
  { id: "10", title: "Deploy de aplicación en Railway", createdAt: "la semana pasada" },
  { id: "11", title: "Crear hook personalizado en React", createdAt: "hace 5 minutos" },
  { id: "12", title: "Manejo de errores en async/await", createdAt: "hace 30 minutos" },
  { id: "13", title: "Cómo usar Zustand en React", createdAt: "hace 1 hora" },
  { id: "14", title: "Configurar ESLint y Prettier", createdAt: "ayer" },
  { id: "15", title: "Cómo funciona el Virtual DOM", createdAt: "ayer" },
  { id: "16", title: "Patrones de diseño en TypeScript", createdAt: "hace 2 días" },
  { id: "17", title: "Introducción a Docker para devs", createdAt: "hace 2 días" },
  { id: "18", title: "Cómo usar GitHub Actions", createdAt: "hace 3 días" },
  { id: "19", title: "Lazy loading en React", createdAt: "hace 4 días" },
  { id: "20", title: "Gestión de estado global con Redux", createdAt: "la semana pasada" },
  { id: "21", title: "Animaciones con Framer Motion", createdAt: "hace 10 minutos" },
  { id: "22", title: "Cómo usar Context API correctamente", createdAt: "hace 45 minutos" },
  { id: "23", title: "Diferencia entre SQL y NoSQL", createdAt: "hace 2 horas" },
  { id: "24", title: "Configurar Tailwind CSS en Vite", createdAt: "ayer" },
  { id: "25", title: "Cómo funciona el event loop en JS", createdAt: "ayer" },
  { id: "26", title: "Principios SOLID en JavaScript", createdAt: "hace 2 días" },
  { id: "27", title: "Testing con Vitest y Testing Library", createdAt: "hace 3 días" },
  { id: "28", title: "Cómo hacer un CRUD con Prisma", createdAt: "hace 3 días" },
  { id: "29", title: "Server Side Rendering con Next.js", createdAt: "hace 5 días" },
  { id: "30", title: "Cómo usar Redis para cacheo", createdAt: "la semana pasada" },
  { id: "31", title: "Accesibilidad en aplicaciones web", createdAt: "hace 15 minutos" },
  { id: "32", title: "Cómo optimizar el rendimiento en React", createdAt: "hace 1 hora" },
  { id: "33", title: "Introducción a GraphQL", createdAt: "hace 2 horas" },
  { id: "34", title: "Cómo usar variables de entorno", createdAt: "ayer" },
  { id: "35", title: "Diferencia entre cookies y localStorage", createdAt: "ayer" },
  { id: "36", title: "Cómo hacer un drag and drop en React", createdAt: "hace 2 días" },
  { id: "37", title: "Internacionalización con i18n", createdAt: "hace 3 días" },
  { id: "38", title: "Cómo usar Web Workers", createdAt: "hace 4 días" },
  { id: "39", title: "Microservicios con Node.js", createdAt: "hace 5 días" },
  { id: "40", title: "Cómo hacer un sistema de roles", createdAt: "la semana pasada" },
  { id: "41", title: "Formularios con React Hook Form", createdAt: "hace 5 minutos" },
  { id: "42", title: "Cómo usar Suspense en React", createdAt: "hace 30 minutos" },
  { id: "43", title: "Introducción a Kubernetes", createdAt: "hace 3 horas" },
  { id: "44", title: "Cómo funciona CORS", createdAt: "ayer" },
  { id: "45", title: "Diferencia entre REST y GraphQL", createdAt: "ayer" },
  { id: "46", title: "Cómo usar Stripe en Node.js", createdAt: "hace 2 días" },
  { id: "47", title: "Cómo proteger rutas en React Router", createdAt: "hace 3 días" },
  { id: "48", title: "Cómo usar WebSockets con Socket.io", createdAt: "hace 4 días" },
  { id: "49", title: "CI/CD con GitHub Actions y Railway", createdAt: "hace 5 días" },
  { id: "50", title: "Cómo escalar una aplicación Node.js", createdAt: "la semana pasada" },
];